import { access, chmod, mkdir, readFile, writeFile } from "node:fs/promises";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { dirname, join, resolve } from "node:path";

const execFileAsync = promisify(execFile);
const START_MARKER = "# >>> skillspace managed hook >>>";
const END_MARKER = "# <<< skillspace managed hook <<<";

export interface InstalledSkill {
  name: string;
  skill: string;
  version: string;
}

export interface IntegrationResult {
  pluginPath: string;
  hookPath: string | null;
}

export const OPENCODE_PLUGIN_SOURCE = `// Generated by SkillRoster. Safe to commit with the project.
// Records only skill identity, version, session ID, and time. Prompts and source are never copied.
import { mkdir, readFile, writeFile } from "node:fs/promises"
import { join } from "node:path"

const pending = new Map()

async function readInstalled(worktree) {
  try {
    return JSON.parse(await readFile(join(worktree, ".skillspace", "installed.json"), "utf8"))
  } catch {
    return { skills: [] }
  }
}

function eventId(sessionId, callId) {
  return ["event", sessionId, callId, Date.now()]
    .join("-")
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
}

export const SkillSpaceEvidence = async ({ worktree }) => ({
  "tool.execute.before": async (input, output) => {
    if (input.tool !== "skill") return
    const name = output?.args?.name
    if (typeof name !== "string" || !name) return
    pending.set(input.callID, {
      name,
      sessionId: input.sessionID || "unknown-session",
      callId: input.callID || String(Date.now()),
    })
  },
  "tool.execute.after": async (input) => {
    if (input.tool !== "skill") return
    const used = pending.get(input.callID)
    pending.delete(input.callID)
    if (!used) return

    try {
      const manifest = await readInstalled(worktree)
      const installed = manifest.skills.find((item) => item.name === used.name)
      if (!installed) return
      const directory = join(worktree, ".skillspace", "events")
      await mkdir(directory, { recursive: true })
      const id = eventId(used.sessionId, used.callId)
      const event = {
        id,
        sessionId: used.sessionId,
        skill: installed.skill,
        version: installed.version,
        usedAt: new Date().toISOString(),
        privacy: { promptStored: false, sourceStored: false },
      }
      await writeFile(join(directory, id + ".json"), JSON.stringify(event, null, 2) + "\\n", "utf8")
    } catch {
      // Evidence collection must never break an OpenCode tool call.
    }
  },
})
`;

async function exists(path: string): Promise<boolean> {
  return access(path).then(
    () => true,
    () => false,
  );
}

async function resolveGitHookPath(projectRoot: string): Promise<string | null> {
  try {
    const { stdout } = await execFileAsync("git", ["rev-parse", "--git-path", "hooks/post-commit"], {
      cwd: projectRoot,
      windowsHide: true,
    });
    const value = stdout.trim();
    return resolve(projectRoot, value);
  } catch {
    return null;
  }
}

function withManagedHook(existing: string): string {
  const managed = `${START_MARKER}\nproject_root="$(git rev-parse --show-toplevel 2>/dev/null)"\ncommit_sha="$(git rev-parse HEAD 2>/dev/null)"\nif command -v skillspace >/dev/null 2>&1 && [ -n "$project_root" ] && [ -n "$commit_sha" ]; then\n  skillspace evidence flush --directory "$project_root" --commit "$commit_sha" >/dev/null 2>&1 || true\nfi\n${END_MARKER}`;
  const withoutManaged = existing.replace(
    new RegExp(`${START_MARKER.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}[\\s\\S]*?${END_MARKER.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\s*`, "g"),
    "",
  );
  const base = withoutManaged.trim()
    ? withoutManaged.trimEnd()
    : "#!/bin/sh";
  return `${base}\n\n${managed}\n`;
}

export async function writeInstalledSkillManifest(
  projectRoot: string,
  skills: InstalledSkill[],
): Promise<string> {
  const path = join(resolve(projectRoot), ".skillspace", "installed.json");
  await mkdir(dirname(path), { recursive: true });
  await writeFile(
    path,
    `${JSON.stringify({ version: 1, skills: [...skills].sort((a, b) => a.name.localeCompare(b.name)) }, null, 2)}\n`,
    "utf8",
  );
  return path;
}

export async function installSkillSpaceIntegration(projectRoot: string): Promise<IntegrationResult> {
  const root = resolve(projectRoot);
  const pluginPath = join(root, ".opencode", "plugins", "skillspace.js");
  await mkdir(dirname(pluginPath), { recursive: true });
  await writeFile(pluginPath, OPENCODE_PLUGIN_SOURCE, "utf8");
  await mkdir(join(root, ".skillspace", "events"), { recursive: true });

  const gitignorePath = join(root, ".gitignore");
  const gitignore = (await exists(gitignorePath)) ? await readFile(gitignorePath, "utf8") : "";
  const ignored = [".skillspace/events/", ".skillspace/installed.json"];
  const missing = ignored.filter(
    (entry) => !gitignore.split(/\r?\n/).some((line) => line.trim() === entry),
  );
  if (missing.length) {
    const prefix = gitignore.length && !gitignore.endsWith("\n") ? "\n" : "";
    await writeFile(gitignorePath, `${gitignore}${prefix}${missing.join("\n")}\n`, "utf8");
  }

  const hookPath = await resolveGitHookPath(root);
  if (hookPath) {
    await mkdir(dirname(hookPath), { recursive: true });
    const existing = (await exists(hookPath)) ? await readFile(hookPath, "utf8") : "";
    await writeFile(hookPath, withManagedHook(existing), "utf8");
    await chmod(hookPath, 0o755).catch(() => undefined);
  }

  return { pluginPath, hookPath };
}
